export default {
    BlockEmpty: -1,
    BlockHeadline: 0,
    BlockParagraph: 1,
    BlockComment: 2,
    BlockKeyword: 3,
    BlockFixedWidthAreas: 4,
    BlockClock: 5,
    BlockPlanning: 6,
    BlockBlock: 7,
    BlockList: 8,
    BlockHorizontal: 9,
    BlockTable: 10,
    BlockFootnote: 11,
    BlockDrawer: 12,
}